exports = {

	"groups" : {

		"pointers"  : {

			"images" : [
				'pointerContextMenu',
				'pointerCrossHair',
				'pointerDetachedPanel',
				'pointerTab',
				'pointerTarget'
			]

		},

		"catalogueStatus" : {

			"options" : {
				"validateWidth" : 13,
				"validateHeight" : 13
			},

			"images" : [
				'catalogueStatusBatchRenderComplete',
				'catalogueStatusBatchRenderRunning',
				'catalogueStatusDisk',
				'catalogueStatusDisplay',
				'catalogueStatusInteractiveRenderComplete',
				'catalogueStatusInteractiveRenderRunning'
			]
		},

		"others" : {

			"images" : [
				'addObjects',
				'arrowDown10',
				'arrowLeft10',
				'arrowRight10',
				'arrowUp10',
				'bookmarkStar',
				'bookmarkStar2',
				'bookmarks',
				'boxInNode',
				'boxNode',
				'boxOutNode',
				'cameraOff',
				'cameraOn',
				'checkBoxChecked',
				'checkBoxCheckedDisabled',
				'checkBoxCheckedHover',
				'checkBoxUnchecked',
				'checkBoxUncheckedDisabled',
				'checkBoxUncheckedHover',
				'classVectorParameterHandle',
				'clippingOff',
				'clippingOn',
				'collapsibleArrowDown',
				'collapsibleArrowDownHover',
				'collapsibleArrowRight',
				'collapsibleArrowRightHover',
				'debugNotification',
				'delete',
				'deleteSmall',
				'drawingStyles',
				'duplicate',
				'editScopeNode',
				'editScopeProcessorNode',
				'errorNotification',
				'errorNotificationSmall',
				'expansion',
				'export',
				'exposureOff',
				'exposureOn',
				'extract',
				'failure',
				'gadgetError',
				'gafferSceneUICameraTool',
				'gafferSceneUICropWindowTool',
				'gafferSceneUIRotateTool',
				'gafferSceneUIScaleTool',
				'gafferSceneUISelectionTool',
				'gafferSceneUITranslateTool',
				'gammaOff',
				'gammaOn',
				'gear',
				'grid',
				'headerSortDown',
				'headerSortUp',
				'info',
				'infoNotification',
				'infoSmall',
				'layoutButton',
				'localDispatcherStatusFailed',
				'localDispatcherStatusKilled',
				'localDispatcherStatusRunning',
				'menuChecked',
				'menuIndicator',
				'menuIndicatorDisabled',
				'minus',
				'move',
				'moveDiagonallyDown',
				'moveDiagonallyUp',
				'moveHorizontally',
				'moveVertically',
				'navigationArrow',
				'nodeSetDriverNodeSelection',
				'nodeSetDriverNodeSet',
				'nodeSetDriverSceneSelectionSource',
				'nodeSetNumericBookmarkSet',
				'nodeSetSourceSet',
				'nodeSetStandardSet',
				'nodes',
				'objects',
				'pathChooser',
				'pathListingList',
				'pathListingTree',
				'pathUpArrow',
				'paths',
				'plug',
				'plugAdder',
				'plugAdderHighlighted',
				'plus',
				'railBottom',
				'railGap',
				'railLine',
				'railMiddle',
				'railSingle',
				'railTop',
				'referenceNode',
				'refresh',
				'removeObjects',
				'reorderVertically',
				'replaceObjects',
				'rgba',
				'scene',
				'sceneInspectorHistory',
				'sceneInspectorInheritance',
				'search',
				'selectionMaskOff',
				'selectionMaskOn',
				'setMembershipDot',
				'shading',
				'shuffleArrow',
				'soloChannel-1',
				'soloChannel0',
				'soloChannel1',
				'soloChannel2',
				'soloChannel3',
				'subMenuArrow',
				'success',
				'successWarning',
				'timeline1',
				'timeline2',
				'timeline3',
				'timelineEnd',
				'timelinePause',
				'timelinePlay',
				'timelineStart',
				'timelineStop',
				'toggleOff',
				'toggleOffDisabled',
				'toggleOffHover',
				'toggleOn',
				'toggleOnDisabled',
				'toggleOnHover',
				'valueChanged',
				'values',
				'viewPause',
				'viewPaused',
				'viewerPause',
				'warningNotification',
				'warningSmall',
			]
		}
	}

}
